
format = """
$env_var\
$os\
$username\
$hostname\
$kubernetes\
$directory\
$symbol($git_branch[](fg:#C0C0C0))\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$package\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true
# command_timeout = 2000
palette = 'nord'

[character]
success_symbol = "╰⎯"
error_symbol = "╰⎯"
# ╭╴ ╰─


[env_var]
symbol = "╭╴"
variable = 'SHELL'
format = "$symbol"
disabled = false


[os]
format = '[$symbol](bold white) '
disabled = true

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'
Unknown = ''

# Shows the username
[username]
style_user = 'yellow bold'
style_root = 'black bold'
format = '[$user](#2883ff)' # 2883ff
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = '[@](white bold)[$hostname](bold blue) '
disabled = false

# Shows current directory
[directory]
truncation_length = 0
# truncation_symbol = '…/'
home_symbol = '~'
# read_only_style = '197'
read_only = '  '
format = '[at](white) [$path]($style)[$read_only]($read_only_style) '
style = '#7ed1fb'
truncate_to_repo = true                                               # yellow bold


# [git_branch]
# style = 'fg:green'
# symbol = ' '
# format = '[on](white) [$symbol$branch ]($style)'


[git_branch]
symbol = " "
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "fg:#1C3A5E bg:#C0C0C0"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
stashed = "[${count}*](green)"
modified = "[${count}+](yellow)"
deleted = "[${count}-](red)"
conflicted = "[${count}~](red)"
ahead = "⇡${count}"
behind = "⇣${count}"
untracked = "[${count}?](blue)"
staged = "[${count}+](green)"

[fill]
symbol = ' '

[python]
style = 'teal'
symbol = ' '
format = '[${symbol}(${version} )(\($virtualenv\) )]($style)'

[kubernetes]
format = 'via [󱃾 $context\($namespace\)](bold purple) '
disabled = true

[lua]
symbol = ' '
disabled = true

[nodejs]
style = 'blue'
symbol = ' '
disabled = false

[golang]
style = 'blue'
symbol = ' '
disabled = true

[haskell]
style = 'blue'
symbol = ' '
disabled = true

[rust]
style = 'orange'
symbol = ' '
disabled = true

[ruby]
style = 'blue'
symbol = ' '
disabled = true

[package]
symbol = '󰏗 '
disabled = true

[aws]
symbol = ' '
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'
disabled = true

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']
disabled = true

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:white'
format = '[$duration]($style)'


[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white = '#D8DEE9'

[palettes.onedark]
dark_blue = '#61afef'
blue = '#56b6c2'
red = '#e06c75'
green = '#98c379'
purple = '#c678dd'
cyan = '#56b6c2'
orange = '#be5046'
yellow = '#e5c07b'
gray = '#828997'
white = '#abb2bf'
black = '#2c323c'
